update script
wileyj/stacks-core pull request #169
Opened 2024-05-07 20:49 UTC by wileyj

### Description

### Applicable issues

- fixes #

### Additional info (benefits, drawbacks, caveats)

### Checklist

- [ ] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

2024-05-07 21:42 UTC, wileyj commented
comment

2024-05-07 21:43 UTC, stacks-foundation commented
comment1

2024-05-07 21:44 UTC, stacks-foundation requested changes
make changes

2024-05-07 21:44 UTC, stacks-foundation commented on test.sh
> +echo "line 2"
```suggestion
echo "line 2"
echo "line 3"
```

2024-05-07 21:48 UTC, stacks-foundation approved these changes, later dismissed
approve

2024-05-07 22:03 UTC, stacks-foundation commented on test-2.sh
> +echo "line 2"
this is a line

2024-05-07 22:25 UTC, stacks-foundation approved these changes
fff

2024-05-07 22:26 UTC, merged

2024-07-09 21:17 UTC, wileyj commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.